force-app/main/default/objects/Billing__c/Billing__c.object-meta.xml
<CustomObject>
    <label>Billing</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Billing Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Billing</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Billing__c/fields/Cash_Withdrawal__c.field-meta.xml
<CustomField>
    <fullName>Cash_Withdrawal__c</fullName>
    <label>Cash Withdrawal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/CreditCard__c.field-meta.xml
<CustomField>
    <fullName>CreditCard__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CreditCard</label>
    <referenceTo>CreditCard__c</referenceTo>
    <relationshipLabel>Billing</relationshipLabel>
    <relationshipName>Billing</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Billing__c/fields/Number_of_transactions__c.field-meta.xml
<CustomField>
    <fullName>Number_of_transactions__c</fullName>
    <label>Number of transactions</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CreditCard__c/CreditCard__c.object-meta.xml
<CustomObject>
    <label>CreditCard</label>
    <nameField>
        <label>CreditCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CreditCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditCard__c/fields/Monthly_one_time_cost__c.field-meta.xml
<CustomField>
    <fullName>Monthly_one_time_cost__c</fullName>
    <label>Monthly one time cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CreditCard__c/fields/monthly_rental_charge__c.field-meta.xml
<CustomField>
    <fullName>monthly_rental_charge__c</fullName>
    <label>monthly rental charge</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CreditCard__c/fields/Transaction_Charges__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Charges__c</fullName>
    <label>Transaction Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/BillingTriggerHandler.cls
public class BillingTriggerHandler {
    
    public static void calculateTotalAmount(List<billing__C> newBills){
        list<billing__C> BillsList = new List<Billing__c>();
        billsList = newBills;
        set<id> creditCardIds = new Set<id>();
        set<string> cardName = new Set<string>();
        
        for(Integer i = 0; i< billsList.size(); i++){
            creditCardIds.add(billsList[i].creditCard__c);
            cardName.add(billsList[i].creditCard__r.name);
            system.debug(billsList[i]);
           
        }
         //step-2
        Map<Id, creditcard__c> billToCreditCardMap = new Map<id, Creditcard__c>();
        List<creditcard__c> creditCards = [select id, transaction_charges__c, monthly_one_time_cost__c, monthly_rental_charge__c 
                                           from creditcard__c
                                           where id in : creditCardIds];
        for(Integer i = 0; i < creditCards.size(); i ++){
            billToCreditCardMap.put(creditCards[i].id, creditcards[i]);
        }
        //step -3
        for(integer i = 0; i < billsList.size(); i ++){
            billsList[i].total_amount__C = billsList[i].cash_withdrawal__C + 
                									billToCreditCardMap.get(billsList[i].creditcard__c).monthly_one_time_cost__c +
                									billTocreditcardMap.get(billsList[i].creditcard__c).monthly_rental_charge__c +
                									billsList[i].Number_of_transactions__c * 
                									billToCreditCardMap.get(billsList[i].creditcard__c).Transaction_charges__C;
    }
    }

}