force-app/main/default/objects/CreditCard__c/CreditCard__c.object-meta.xml
<CustomObject>
    <label>CreditCard</label>
    <nameField>
        <label>CreditCard Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CreditCards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CreditCard__c/fields/Monthly_Rental__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Rental__c</fullName>
    <label>Monthly Rental</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditCard__c/fields/One_Time_Cost__c.field-meta.xml
<CustomField>
    <fullName>One_Time_Cost__c</fullName>
    <label>One Time Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/CreditCard__c/fields/Transaction_Charges__c.field-meta.xml
<CustomField>
    <fullName>Transaction_Charges__c</fullName>
    <label>Transaction Charges</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CreditcardInsert.cls
public class CreditcardInsert {
    public CreditCard__C creditCardRecord;
    
    public void ccInput(string nameInput, Integer monthlyChargeInput,
                       Integer oneTimeCostInput, Decimal transactionInput){
        
        					this.creditCardRecord = new CreditCard__c();
                           creditCardRecord = new CreditCard__C();
                           this.creditCardRecord.name = nameInput;
                           this.creditCardRecord.Monthly_Rental__c = monthlyChargeInput;
                           this.creditCardRecord.One_Time_Cost__c = oneTimeCostInput;
                           this.creditCardRecord.Transaction_Charges__C = transactionInput;
                           
                           insert this.creditcardRecord;
                           
    }

}